baseURL = 'https://ou-joy.github.io'
languageCode = 'zh-tw'
title = 'My Blog'
theme = "PaperMod"
buildDrafts = false 
[[menu.main]]

identifier = "tags"

name = "tags"

url = "/tags/"

weight = 10

[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30 

[params.profileMode]
enabled = true
title = "OU,YOU-JIE"
subtitle = "Studying in Chungming High School."
imageUrl = "img/DSC02038.JPG"
imageWidth = 120
imageHeight = 120
imageTitle = "picture"
[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ou-joy"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@user-bx3fs8bb5z/aboutl"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/oujoy0814?s=21&t=dEsJjXtWHv2nML0WjoVA1Q"

[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結

[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視